/**
 * This file is generated by dconfig2cpp.
 * Command line arguments: ./build/tools/dconfig2cpp/dconfig2cpp ./tests/data/dconf-example_other_app_configure.meta.json -o ./toolGenerate/dconfig2cpp/dconf-example_other_app_configure_meta.hpp
 * Generation time: 2026-01-16T21:21:45
 * JSON file version: 1.0
 *
 * WARNING: DO NOT MODIFY THIS FILE MANUALLY.
 * If you need to change the content, please modify the dconfig2cpp tool.
 */

#ifndef DCONFIG_DCONF-EXAMPLE_OTHER_APP_CONFIGURE_META_H
#define DCONFIG_DCONF-EXAMPLE_OTHER_APP_CONFIGURE_META_H

#include <QThread>
#include <QVariant>
#include <QPointer>
#include <QDebug>
#include <QAtomicPointer>
#include <QAtomicInteger>
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
#include <QProperty>
#endif
#include <QEvent>
#include <DSGApplication>
#include <DConfig>

class dconfig_dconf-example_other_app_configure_meta : public QObject {
    Q_OBJECT

    Q_PROPERTY(QString appPrivate READ appPrivate WRITE setAppPrivate NOTIFY appPrivateChanged RESET resetAppPrivate)
    Q_PROPERTY(QString appPublic READ appPublic WRITE setAppPublic NOTIFY appPublicChanged RESET resetAppPublic)
    Q_CLASSINFO("DConfigKeyList", "appPrivate;appPublic")
    Q_CLASSINFO("DConfigFileName", "dconf-example_other_app_configure.meta")
    Q_CLASSINFO("DConfigFileVersion", "1.0")

public:
    explicit dconfig_dconf-example_other_app_configure_meta(QThread *thread, DTK_CORE_NAMESPACE::DConfigBackend *backend,
                        const QString &name, const QString &appId, const QString &subpath,
                        bool isGeneric, QObject *parent)
                  : QObject(parent), m_data(new Data) {
        m_data->m_userConfig = this;
        m_data->moveToThread(thread);

        if (!thread->isRunning()) {
            qWarning() << QLatin1String("Warning: The provided thread is not running.");
        }
        Q_ASSERT(QThread::currentThread() != thread);
        auto worker = new QObject();
        worker->moveToThread(thread);

        QPointer<Data> safeData(m_data);

        QMetaObject::invokeMethod(worker, [safeData, backend, name, appId, subpath, isGeneric, worker]() mutable {
            delete worker;
            worker = nullptr;

            if (!safeData->m_status.testAndSetOrdered(static_cast<int>(Data::Status::Invalid),
                                                  static_cast<int>(Data::Status::Initializing))) {
                // CAS failed, state already changed - userConfig destructor will handle cleanup
                // Do not attempt to delete here as it would race with destructor
                return;
            }

            DTK_CORE_NAMESPACE::DConfig *config = nullptr;
            if (isGeneric) {
                if (backend) {
                    config = DTK_CORE_NAMESPACE::DConfig::createGeneric(backend, name, subpath, nullptr);
                } else {
                    config = DTK_CORE_NAMESPACE::DConfig::createGeneric(name, subpath, nullptr);
                }
            } else {
                if (backend) {
                    if (appId.isNull()) {
                        config = DTK_CORE_NAMESPACE::DConfig::create(backend, DTK_CORE_NAMESPACE::DSGApplication::id(),
                                                                     name, subpath, nullptr);
                    } else {
                        config = DTK_CORE_NAMESPACE::DConfig::create(backend, appId, name, subpath, nullptr);
                    }
                } else {
                    if (appId.isNull()) {
                        config = DTK_CORE_NAMESPACE::DConfig::create(DTK_CORE_NAMESPACE::DSGApplication::id(),
                                                                     name, subpath, nullptr);
                    } else {
                        config = DTK_CORE_NAMESPACE::DConfig::create(appId, name, subpath, nullptr);
                    }
                }
            }

            if (!config || !config->isValid()) {
                qWarning() << QLatin1String("Failed to create DConfig instance.");

                if (safeData->m_status.testAndSetOrdered(static_cast<int>(Data::Status::Initializing),
                                                         static_cast<int>(Data::Status::Failed))) {
                    if (safeData->m_userConfig) {
                        QPointer<Data> selfData = safeData;
                        QMetaObject::invokeMethod(selfData, [selfData]() {
                            if (selfData && selfData->m_userConfig) {
                                Q_EMIT selfData->m_userConfig->configInitializeFailed();
                            }
                        }, Qt::QueuedConnection);
                    }
                }

                if (config)
                    delete config;

                return;
            }
            config->moveToThread(QThread::currentThread());
            // Initialize through Data class
            safeData->initializeInConfigThread(config);

            // Try to transition from Initializing to Succeeded
            if (safeData->m_status.testAndSetOrdered(static_cast<int>(Data::Status::Initializing),
                                                      static_cast<int>(Data::Status::Succeeded))) {
                // CAS succeeded, connect destroyed signal
                QPointer<Data> selfData = safeData;
                QObject::connect(config, &QObject::destroyed, config, [selfData]() {
                    if (selfData) { 
                        selfData->deleteLater(); }
                });
            } else {
                // CAS failed - state changed (e.g., set to Destroyed)
                // We must clean up the config we just created
                config->deleteLater();
                safeData->deleteLater();
            }
        });
    }
    static dconfig_dconf-example_other_app_configure_meta* create(const QString &appId = {}, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, nullptr, QStringLiteral(u"\u0064\u0063\u006f\u006e\u0066\u002d\u0065\u0078\u0061\u006d\u0070\u006c\u0065\u005f\u006f\u0074\u0068\u0065\u0072\u005f\u0061\u0070\u0070\u005f\u0063\u006f\u006e\u0066\u0069\u0067\u0075\u0072\u0065\u002e\u006d\u0065\u0074\u0061"), appId, subpath, false, parent); }
    static dconfig_dconf-example_other_app_configure_meta* create(DTK_CORE_NAMESPACE::DConfigBackend *backend, const QString &appId = {}, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, backend, QStringLiteral(u"\u0064\u0063\u006f\u006e\u0066\u002d\u0065\u0078\u0061\u006d\u0070\u006c\u0065\u005f\u006f\u0074\u0068\u0065\u0072\u005f\u0061\u0070\u0070\u005f\u0063\u006f\u006e\u0066\u0069\u0067\u0075\u0072\u0065\u002e\u006d\u0065\u0074\u0061"), appId, subpath, false, parent); }
    static dconfig_dconf-example_other_app_configure_meta* createByName(const QString &name, const QString &appId = {}, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, nullptr, name, appId, subpath, false, parent); }
    static dconfig_dconf-example_other_app_configure_meta* createByName(DTK_CORE_NAMESPACE::DConfigBackend *backend, const QString &name, const QString &appId = {}, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, backend, name, appId, subpath, false, parent); }
    static dconfig_dconf-example_other_app_configure_meta* createGeneric(const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, nullptr, QStringLiteral(u"\u0064\u0063\u006f\u006e\u0066\u002d\u0065\u0078\u0061\u006d\u0070\u006c\u0065\u005f\u006f\u0074\u0068\u0065\u0072\u005f\u0061\u0070\u0070\u005f\u0063\u006f\u006e\u0066\u0069\u0067\u0075\u0072\u0065\u002e\u006d\u0065\u0074\u0061"), {}, subpath, true, parent); }
    static dconfig_dconf-example_other_app_configure_meta* create(DTK_CORE_NAMESPACE::DConfigBackend *backend, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, backend, QStringLiteral(u"\u0064\u0063\u006f\u006e\u0066\u002d\u0065\u0078\u0061\u006d\u0070\u006c\u0065\u005f\u006f\u0074\u0068\u0065\u0072\u005f\u0061\u0070\u0070\u005f\u0063\u006f\u006e\u0066\u0069\u0067\u0075\u0072\u0065\u002e\u006d\u0065\u0074\u0061"), {}, subpath, true, parent); }
    static dconfig_dconf-example_other_app_configure_meta* createGenericByName(const QString &name, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, nullptr, name, {}, subpath, true, parent); }
    static dconfig_dconf-example_other_app_configure_meta* createGenericByName(DTK_CORE_NAMESPACE::DConfigBackend *backend, const QString &name, const QString &subpath = {}, QObject *parent = nullptr, QThread *thread = DTK_CORE_NAMESPACE::DConfig::globalThread())
    { return new dconfig_dconf-example_other_app_configure_meta(thread, backend, name, {}, subpath, true, parent); }
    ~dconfig_dconf-example_other_app_configure_meta() {
        int oldStatus = m_data->m_status.fetchAndStoreOrdered(static_cast<int>(Data::Status::Destroyed));

        if (oldStatus == static_cast<int>(Data::Status::Succeeded)) {
            // When Succeeded, release config object only
            auto config = m_data->m_config.loadRelaxed();
            Q_ASSERT(config);
            config->deleteLater();
            // m_data will be deleted by config's destroyed signal
        } else if (oldStatus == static_cast<int>(Data::Status::Failed) ||
                   oldStatus == static_cast<int>(Data::Status::Invalid)) {
            // When Failed or Invalid, directly clean up Data object
            m_data->deleteLater();
        }
    }

    Q_INVOKABLE DTK_CORE_NAMESPACE::DConfig *config() const {
        return m_data->m_config.loadRelaxed();
    }
    Q_INVOKABLE bool isInitializeSucceed() const {
        return m_data->m_status.loadRelaxed() == static_cast<int>(Data::Status::Succeeded);
    }
    Q_INVOKABLE bool isInitializeFailed() const {
        return m_data->m_status.loadRelaxed() == static_cast<int>(Data::Status::Failed);
    }
    Q_INVOKABLE bool isInitializing() const {
        return m_data->m_status.loadRelaxed() == static_cast<int>(Data::Status::Initializing);
    }

    Q_INVOKABLE QStringList keyList() const {
        return {
            QStringLiteral("appPrivate"),
            QStringLiteral("appPublic")
        };
    }

    Q_INVOKABLE bool isDefaultValue(const QString &key) const {
        if (key == QStringLiteral("appPrivate"))
            return appPrivateIsDefaultValue();
        if (key == QStringLiteral("appPublic"))
            return appPublicIsDefaultValue();
        return false;
    }

    QString appPrivate() const
    {
        return m_data->p_appPrivate;
    }
    void setAppPrivate(const QString &value) {
        auto oldValue = m_data->p_appPrivate;
        m_data->p_appPrivate = value;
        m_data->markPropertySet(0);
        if (auto config = m_data->m_config.loadRelaxed()) {
            QMetaObject::invokeMethod(config, [config, value]() {
                config->setValue(QStringLiteral("appPrivate"), value);
            });
        }
        if (m_data->p_appPrivate != oldValue) {
            Q_EMIT appPrivateChanged();
            Q_EMIT valueChanged(QStringLiteral("appPrivate"), value);
        }
    }
    void resetAppPrivate() {
        if (auto config = m_data->m_config.loadRelaxed()) {
            QMetaObject::invokeMethod(config, [config]() {
                config->reset(QStringLiteral("appPrivate"));
            });
        }
    }
    Q_INVOKABLE bool appPrivateIsDefaultValue() const
    {
        return !m_data->testPropertySet(0);
    }
    QString appPublic() const
    {
        return m_data->p_appPublic;
    }
    void setAppPublic(const QString &value) {
        auto oldValue = m_data->p_appPublic;
        m_data->p_appPublic = value;
        m_data->markPropertySet(1);
        if (auto config = m_data->m_config.loadRelaxed()) {
            QMetaObject::invokeMethod(config, [config, value]() {
                config->setValue(QStringLiteral("appPublic"), value);
            });
        }
        if (m_data->p_appPublic != oldValue) {
            Q_EMIT appPublicChanged();
            Q_EMIT valueChanged(QStringLiteral("appPublic"), value);
        }
    }
    void resetAppPublic() {
        if (auto config = m_data->m_config.loadRelaxed()) {
            QMetaObject::invokeMethod(config, [config]() {
                config->reset(QStringLiteral("appPublic"));
            });
        }
    }
    Q_INVOKABLE bool appPublicIsDefaultValue() const
    {
        return !m_data->testPropertySet(1);
    }
protected:
    bool event(QEvent *e) override {
        if (e->type() == QEvent::ThreadChange) {
            Q_ASSERT_X(false, "dconfig_dconf-example_other_app_configure_meta", "Moving dconfig_dconf-example_other_app_configure_meta to another thread is forbidden!");
        }
        return QObject::event(e);
    }

Q_SIGNALS:
    void configInitializeFailed();
    void configInitializeSucceed(DTK_CORE_NAMESPACE::DConfig *config);
    void valueChanged(const QString &key, const QVariant &value);
    void appPrivateChanged();
    void appPublicChanged();

private:
    // Prevent external moveToThread calls
    using QObject::moveToThread;
    class Data : public QObject {
    public:
        enum class Status {
            Invalid = 0,
            Initializing = 1,
            Succeeded = 2,
            Failed = 3,
            Destroyed = 4
        };

        explicit Data()
            : QObject(nullptr) {}

        QAtomicPointer<DTK_CORE_NAMESPACE::DConfig> m_config = nullptr;
        QAtomicInteger<int> m_status = static_cast<int>(Status::Invalid);
        QPointer<dconfig_dconf-example_other_app_configure_meta> m_userConfig = nullptr;
        QAtomicInteger<quint32> m_propertySetStatus0 = 0;

        // Property storage
        // Default value: "appPrivate"
        QString p_appPrivate { QStringLiteral(u"\u0061\u0070\u0070\u0050\u0072\u0069\u0076\u0061\u0074\u0065") };
        // Default value: "publicValue"
        QString p_appPublic { QStringLiteral(u"\u0070\u0075\u0062\u006c\u0069\u0063\u0056\u0061\u006c\u0075\u0065") };

        inline void initializeInConfigThread(DTK_CORE_NAMESPACE::DConfig *config) {
            Q_ASSERT(!m_config.loadRelaxed());
            m_config.storeRelaxed(config);
            // Connect signals early - use QPointer to protect Data lifetime
            QPointer<Data> selfData(this);
            QObject::connect(config, &DTK_CORE_NAMESPACE::DConfig::valueChanged, config, [selfData](const QString &key) {
                if (selfData) selfData->updateValue(key);
            });
            if (testPropertySet(0)) {
                config->setValue(QStringLiteral("appPrivate"), QVariant::fromValue(p_appPrivate));
            } else {
                updateValue(QStringLiteral("appPrivate"), QVariant::fromValue(p_appPrivate));
            }
            if (testPropertySet(1)) {
                config->setValue(QStringLiteral("appPublic"), QVariant::fromValue(p_appPublic));
            } else {
                updateValue(QStringLiteral("appPublic"), QVariant::fromValue(p_appPublic));
            }
        }

        inline void updateValue(const QString &key, const QVariant &fallback = QVariant()) {
            auto config = m_config.loadRelaxed();
            if (!config) return;
            const QVariant &v = config->value(key, fallback);
            if (key == QStringLiteral("appPrivate")) {
                markPropertySet(0, !config->isDefaultValue(key));
                updateProperty(key, v);
                return;
            }
            if (key == QStringLiteral("appPublic")) {
                markPropertySet(1, !config->isDefaultValue(key));
                updateProperty(key, v);
                return;
            }
        }

        inline void updateProperty(const QString &key, const QVariant &v) {
            if (key == QStringLiteral("appPrivate")) {
                QString nv = qvariant_cast<QString>(v);
                if (p_appPrivate != nv) {
                    p_appPrivate = nv;
                    if (m_userConfig) {
                        QPointer<Data> selfData(this);
                        // Emit signals on main thread (userConfig's thread)
                        QMetaObject::invokeMethod(m_userConfig, [selfData, key, v]() {
                            if (selfData && selfData->m_userConfig) {
                                Q_EMIT selfData->m_userConfig->appPrivateChanged();
                                Q_EMIT selfData->m_userConfig->valueChanged(key, v);
                            }
                        }, Qt::QueuedConnection);
                    }
                }
                return;
            }
            if (key == QStringLiteral("appPublic")) {
                QString nv = qvariant_cast<QString>(v);
                if (p_appPublic != nv) {
                    p_appPublic = nv;
                    if (m_userConfig) {
                        QPointer<Data> selfData(this);
                        // Emit signals on main thread (userConfig's thread)
                        QMetaObject::invokeMethod(m_userConfig, [selfData, key, v]() {
                            if (selfData && selfData->m_userConfig) {
                                Q_EMIT selfData->m_userConfig->appPublicChanged();
                                Q_EMIT selfData->m_userConfig->valueChanged(key, v);
                            }
                        }, Qt::QueuedConnection);
                    }
                }
                return;
            }
        }

        inline void markPropertySet(const int index, bool on = true) {
            if (index < 32) {
                if (on)
                    m_propertySetStatus0.fetchAndOrOrdered(1 << (index - 0));
                else
                    m_propertySetStatus0.fetchAndAndOrdered(~(1 << (index - 0)));
                return;
            }
            Q_UNREACHABLE();
        }

        inline bool testPropertySet(const int index) const {
            if (index < 32) {
                return (m_propertySetStatus0.loadRelaxed() & (1 << (index - 0)));
            }
            Q_UNREACHABLE();
        }
    };

    Data *m_data;
};

#endif // DCONFIG_DCONF-EXAMPLE_OTHER_APP_CONFIGURE_META_H
